# -*- coding: utf-8 -*-
"""DGIM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CXHj7cH5KrcWKZ4NGZ6pvriGm43gKBsX
"""

class DGIM:
    def __init__(self, window_size):
        self.window_size = window_size
        self.buckets = []
        self.current_time = 0

    def _remove_old_buckets(self):
        self.buckets = [b for b in self.buckets if b[1] > self.current_time - self.window_size]

    def _merge_buckets(self):
        i = 0
        while i < len(self.buckets) - 2:
            if self.buckets[i][0] == self.buckets[i+1][0] == self.buckets[i+2][0]:
                new_bucket = (self.buckets[i][0] * 2, self.buckets[i+1][1])
                self.buckets.pop(i)
                self.buckets.pop(i)
                self.buckets.insert(i, new_bucket)
            else:
                i += 1

    def add_bit(self, bit):
        self.current_time += 1
        if bit == 1:
            self.buckets.insert(0, (1, self.current_time))
            self._merge_buckets()
        self._remove_old_buckets()

    def count_ones(self):
        total = 0
        for i, (size, _) in enumerate(self.buckets):
            if i == len(self.buckets) - 1:
                total += size // 2
            else:
                total += size
        return total

# -------------------------
# ENTER YOUR BIT STREAM HERE
# -------------------------

dgim = DGIM(10)     # window size (N)
stream = [1,0,1,1,0,1,0,0,1,1]  # <--- change this

for bit in stream:
    dgim.add_bit(bit)

print("Estimated count of 1s in last 10 bits =", dgim.count_ones())

